// Code generated by protoc-gen-go. DO NOT EDIT.
// source: frontend.proto

/*
Package frontend is a generated protocol buffer package.

It is generated from these files:
	frontend.proto

It has these top-level messages:
	TestMsg
*/
package frontend

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TestMsg struct {
	Text string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
}

func (m *TestMsg) Reset()                    { *m = TestMsg{} }
func (m *TestMsg) String() string            { return proto.CompactTextString(m) }
func (*TestMsg) ProtoMessage()               {}
func (*TestMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TestMsg) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*TestMsg)(nil), "frontend.testMsg")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FrontendService service

type FrontendServiceClient interface {
	Test(ctx context.Context, in *TestMsg, opts ...grpc.CallOption) (*TestMsg, error)
}

type frontendServiceClient struct {
	cc *grpc.ClientConn
}

func NewFrontendServiceClient(cc *grpc.ClientConn) FrontendServiceClient {
	return &frontendServiceClient{cc}
}

func (c *frontendServiceClient) Test(ctx context.Context, in *TestMsg, opts ...grpc.CallOption) (*TestMsg, error) {
	out := new(TestMsg)
	err := grpc.Invoke(ctx, "/frontend.FrontendService/test", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FrontendService service

type FrontendServiceServer interface {
	Test(context.Context, *TestMsg) (*TestMsg, error)
}

func RegisterFrontendServiceServer(s *grpc.Server, srv FrontendServiceServer) {
	s.RegisterService(&_FrontendService_serviceDesc, srv)
}

func _FrontendService_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendServiceServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frontend.FrontendService/Test",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendServiceServer).Test(ctx, req.(*TestMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _FrontendService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "frontend.FrontendService",
	HandlerType: (*FrontendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "test",
			Handler:    _FrontendService_Test_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "frontend.proto",
}

func init() { proto.RegisterFile("frontend.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 109 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x2b, 0xca, 0xcf,
	0x2b, 0x49, 0xcd, 0x4b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0x64,
	0xb9, 0xd8, 0x4b, 0x52, 0x8b, 0x4b, 0x7c, 0x8b, 0xd3, 0x85, 0x84, 0xb8, 0x58, 0x4a, 0x52, 0x2b,
	0x4a, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x23, 0x47, 0x2e, 0x7e, 0x37, 0xa8,
	0xd2, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x3d, 0x90, 0xb2, 0xe2, 0x12, 0x21, 0x41,
	0x3d, 0xb8, 0xa1, 0x50, 0x13, 0xa4, 0x30, 0x85, 0x94, 0x18, 0x92, 0xd8, 0xc0, 0x56, 0x1a, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xbf, 0xda, 0xa1, 0x8b, 0x84, 0x00, 0x00, 0x00,
}
