// Code generated by protoc-gen-go. DO NOT EDIT.
// source: frontend.proto

/*
Package frontend is a generated protocol buffer package.

It is generated from these files:
	frontend.proto

It has these top-level messages:
	TestMsg
	ServiceRequest
	ServiceResponse
*/
package frontend

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServiceName int32

const (
	ServiceName_NONE ServiceName = 0
	ServiceName_BLOG ServiceName = 1
	ServiceName_USER ServiceName = 2
)

var ServiceName_name = map[int32]string{
	0: "NONE",
	1: "BLOG",
	2: "USER",
}
var ServiceName_value = map[string]int32{
	"NONE": 0,
	"BLOG": 1,
	"USER": 2,
}

func (x ServiceName) String() string {
	return proto.EnumName(ServiceName_name, int32(x))
}
func (ServiceName) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type TestMsg struct {
	Text string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
}

func (m *TestMsg) Reset()                    { *m = TestMsg{} }
func (m *TestMsg) String() string            { return proto.CompactTextString(m) }
func (*TestMsg) ProtoMessage()               {}
func (*TestMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TestMsg) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type ServiceRequest struct {
	Name ServiceName `protobuf:"varint,1,opt,name=name,enum=frontend.ServiceName" json:"name,omitempty"`
}

func (m *ServiceRequest) Reset()                    { *m = ServiceRequest{} }
func (m *ServiceRequest) String() string            { return proto.CompactTextString(m) }
func (*ServiceRequest) ProtoMessage()               {}
func (*ServiceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ServiceRequest) GetName() ServiceName {
	if m != nil {
		return m.Name
	}
	return ServiceName_NONE
}

type ServiceResponse struct {
	Url string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
}

func (m *ServiceResponse) Reset()                    { *m = ServiceResponse{} }
func (m *ServiceResponse) String() string            { return proto.CompactTextString(m) }
func (*ServiceResponse) ProtoMessage()               {}
func (*ServiceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ServiceResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*TestMsg)(nil), "frontend.testMsg")
	proto.RegisterType((*ServiceRequest)(nil), "frontend.ServiceRequest")
	proto.RegisterType((*ServiceResponse)(nil), "frontend.ServiceResponse")
	proto.RegisterEnum("frontend.ServiceName", ServiceName_name, ServiceName_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FrontendService service

type FrontendServiceClient interface {
	Test(ctx context.Context, in *TestMsg, opts ...grpc.CallOption) (*TestMsg, error)
	GetServiceURL(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error)
}

type frontendServiceClient struct {
	cc *grpc.ClientConn
}

func NewFrontendServiceClient(cc *grpc.ClientConn) FrontendServiceClient {
	return &frontendServiceClient{cc}
}

func (c *frontendServiceClient) Test(ctx context.Context, in *TestMsg, opts ...grpc.CallOption) (*TestMsg, error) {
	out := new(TestMsg)
	err := grpc.Invoke(ctx, "/frontend.FrontendService/test", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendServiceClient) GetServiceURL(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := grpc.Invoke(ctx, "/frontend.FrontendService/getServiceURL", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FrontendService service

type FrontendServiceServer interface {
	Test(context.Context, *TestMsg) (*TestMsg, error)
	GetServiceURL(context.Context, *ServiceRequest) (*ServiceResponse, error)
}

func RegisterFrontendServiceServer(s *grpc.Server, srv FrontendServiceServer) {
	s.RegisterService(&_FrontendService_serviceDesc, srv)
}

func _FrontendService_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendServiceServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frontend.FrontendService/Test",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendServiceServer).Test(ctx, req.(*TestMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendService_GetServiceURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendServiceServer).GetServiceURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frontend.FrontendService/GetServiceURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendServiceServer).GetServiceURL(ctx, req.(*ServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FrontendService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "frontend.FrontendService",
	HandlerType: (*FrontendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "test",
			Handler:    _FrontendService_Test_Handler,
		},
		{
			MethodName: "getServiceURL",
			Handler:    _FrontendService_GetServiceURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "frontend.proto",
}

func init() { proto.RegisterFile("frontend.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x2b, 0xca, 0xcf,
	0x2b, 0x49, 0xcd, 0x4b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0x64,
	0xb9, 0xd8, 0x4b, 0x52, 0x8b, 0x4b, 0x7c, 0x8b, 0xd3, 0x85, 0x84, 0xb8, 0x58, 0x4a, 0x52, 0x2b,
	0x4a, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x6b, 0x2e, 0xbe, 0xe0, 0xd4,
	0xa2, 0xb2, 0xcc, 0xe4, 0xd4, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x4d, 0x2e, 0x96,
	0xbc, 0xc4, 0xdc, 0x54, 0xb0, 0x2a, 0x3e, 0x23, 0x51, 0x3d, 0xb8, 0xc9, 0x50, 0x75, 0x7e, 0x89,
	0xb9, 0xa9, 0x41, 0x60, 0x25, 0x4a, 0xca, 0x5c, 0xfc, 0x70, 0xcd, 0xc5, 0x05, 0xf9, 0x79, 0xc5,
	0xa9, 0x42, 0x02, 0x5c, 0xcc, 0xa5, 0x45, 0x39, 0x50, 0x2b, 0x40, 0x4c, 0x2d, 0x6d, 0x2e, 0x6e,
	0x24, 0x9d, 0x42, 0x1c, 0x5c, 0x2c, 0x7e, 0xfe, 0x7e, 0xae, 0x02, 0x0c, 0x20, 0x96, 0x93, 0x8f,
	0xbf, 0xbb, 0x00, 0x23, 0x88, 0x15, 0x1a, 0xec, 0x1a, 0x24, 0xc0, 0x64, 0xd4, 0xc9, 0xc8, 0xc5,
	0xef, 0x06, 0xb5, 0x10, 0xaa, 0x4b, 0x48, 0x0f, 0xe4, 0xec, 0xe2, 0x12, 0x21, 0x41, 0x84, 0x53,
	0xa0, 0x3e, 0x92, 0xc2, 0x14, 0x52, 0x62, 0x10, 0x72, 0xe3, 0xe2, 0x4d, 0x4f, 0x2d, 0x81, 0xea,
	0x0e, 0x0d, 0xf2, 0x11, 0x92, 0xc0, 0xf0, 0x03, 0xd4, 0xaf, 0x52, 0x92, 0x58, 0x64, 0x20, 0x1e,
	0x51, 0x62, 0x48, 0x62, 0x03, 0x07, 0xa5, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x38, 0x6b,
	0x50, 0x5c, 0x01, 0x00, 0x00,
}
